// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbanoxgarosmqvbjrlox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiYW5veGdhcm9zbXF2YmpybG94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTA0NTksImV4cCI6MjA2MzgyNjQ1OX0.wwpJcPRX0h5X7Ac3v_LB-4zvHLitvBzA5oKtJtaKfic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);